'use client';
import { ArrowUpRight, ArrowDown, Code2, Sparkles, Cloud, GraduationCap, Users, Heart, Check, Copy, Mail, Award, Braces } from 'lucide-react';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog, DialogContent, DialogTitle, DialogDescription} from '@/components/ui/dialog';

const projects=[
 {name:'SPILTO Connections',short:'SPILTO',second:'Connections',category:'AI applications',label:'INDEPENDENT / AI MEETING ASSISTANT',tone:'face-ai',line:'Meet. Understand. Take action.',description:'A meeting-assistant project that turns conversations into structured summaries, decisions, and action items for review.',stack:['React','TypeScript','Node.js','Gemini API'],live:'https://spilto-connections-1.onrender.com',role:'Independent developer',problem:'Important decisions and follow-up tasks can get lost in meeting conversations.',approach:'Built a meeting-assistant application around transcript processing, structured AI outputs, and a human review step. The TechBharat Cohort 2 Buildathon submission and the live SPILTO application share the idea, with different backend implementations.',features:['Transcript and audio workflows','Summaries, decisions, and action items','Review and approval before external actions','Multilingual interaction'],note:'The listed stack describes the hackathon version. The live version uses a different backend. The demo requires sign-in and may take a moment to wake up. Hackathon source is private.'},
 {name:'RetailMate',short:'RetailMate',category:'Cloud & systems',label:'TEAM / FINAL-YEAR PROJECT',tone:'face-cloud',line:'Smart inventory. Seamless retail.',description:'A cloud-backed inventory application. I designed the interface and workflow, and developed the frontend as part of the team.',stack:['React','AWS Lambda','DynamoDB','Terraform'],repo:'https://github.com/klu-2200031955/Final_Year_Project',role:'Frontend developer · Interface & workflow design',problem:'Retail inventory needs a clear way to track items, update quantities, and find the right records.',approach:'Planned how users move through the application, designed the interface, and built the React frontend. The team project connects inventory operations to an AWS serverless backend, with Cognito authentication and infrastructure defined in Terraform.',features:['Sign-up and sign-in flows','Add, edit, and delete inventory items','Quantity updates and item search','Frontend integration with inventory APIs'],note:'A team project. My contribution covers design, application workflow, and frontend development; the full AWS architecture is a team outcome.'},
 {name:'FinDash',short:'FinDash',category:'Web development',label:'INDEPENDENT / ACADEMIC PROJECT',tone:'face-finance',line:'A clearer view of the numbers.',description:'An interactive finance dashboard for exploring transactions, income, expenses, and spending patterns.',stack:['React','Tailwind CSS','Recharts','Context API'],live:'https://finance-dashboard-one-beta-90.vercel.app/',repo:'https://github.com/Rakeshnamburi/finance-dashboard',role:'Independent developer',problem:'Financial records are easier to understand when transactions and trends can be explored in one place.',approach:'Developed a frontend application using React Context and useReducer for state management, with charts, transaction filtering, and data exports.',features:['Income, expense, and balance summaries','Search, sorting, and transaction filters','Interactive spending visualizations','CSV and JSON exports'],note:'A frontend demonstration using local application state. Admin and viewer modes demonstrate UI behavior; they are not backend-enforced access controls.'},
 {name:'ElectroFlow AI',short:'ElectroFlow',second:'AI',category:'Web development',label:'INDEPENDENT / LIVE APPLICATION',tone:'face-electro',line:'An independent exploration in building.',description:'An independently developed web application with an operations sign-in interface and multilingual entry experience.',stack:['Web application','English · Telugu · Hindi'],live:'https://electroflow-ai.vercel.app/',role:'Independent developer',problem:'Exploring how to make an application’s entry experience accessible across languages.',approach:'Developed and deployed ElectroFlow AI. The public entry page includes language selection, email/password sign-in, account creation, and password-recovery entry points.',features:['English, Telugu, and Hindi language options','Operations sign-in interface','Account creation entry point','Deployed application on Vercel'],note:'The application requires sign-in. This overview describes its public interface.'}
];
const credentials=[
 ['Microsoft','Fabric Analytics Engineer Associate','Professional certification · Aug 2026','microsoft-fabric.pdf'],
 ['AWS','Certified Cloud Practitioner','Professional certification · May 2024','aws-cloud-practitioner.pdf'],
 ['ServiceNow','Certified System Administrator','Professional certification · Jun 2025','servicenow-csa.pdf'],
 ['Salesforce','AI Associate','Certification earned · Oct 2024','salesforce-ai-associate.pdf'],
 ['Automation Anywhere','Essentials RPA Professional','2023 credential edition','automation-anywhere-rpa.pdf'],
 ['Fintech Council of India','Fintech Professional Certificate','Blockchain, DeFi & Fintech Capstone · Jul 2024','fintech-professional.pdf'],
 ['Amaravati Quantum Valley · Qubitech · WISER','Quantum Algorithm Fundamentals','Six-week hands-on training · Jun 2026','quantum-training.pdf']
];
function External({href,children,className='text-link'}:{href:string;children:React.ReactNode;className?:string}){return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={15}/></a>}
export default function Home(){
 const [filter,setFilter]=useState('All work'); const [selected,setSelected]=useState<number|null>(null); const [copied,setCopied]=useState(false); const [copyError,setCopyError]=useState(false);
 const project=selected===null?null:projects[selected];
 async function copyEmail(){try{await navigator.clipboard.writeText('rakeshnamburi2k4@gmail.com');setCopied(true);setCopyError(false);setTimeout(()=>setCopied(false),2500)}catch{setCopyError(true)}}
 return <>
 <a href="#main" className="skip-link">Skip to content</a>
 <header className="site-header wrap"><a className="wordmark" href="#" aria-label="Namburi Rakesh, back to top">nr<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Selected work</a><a href="#about">About</a><a href="#contact" className="nav-contact">Let’s talk <ArrowUpRight size={15}/></a></nav></header>
 <main id="main">
 <section className="hero wrap">
 <div className="eyebrow"><span className="status-dot"/> OPEN TO GRADUATE OPPORTUNITIES <span className="hero-location">ANDHRA PRADESH, INDIA</span></div>
 <div className="hero-grid"><div><p className="intro">Hello, I’m Namburi Rakesh.</p><h1>Curious mind.<br/><em>Practical builder.</em></h1><p className="hero-copy">I turn ideas into interfaces and intelligent applications. Exploring the space between frontend engineering, AI, and the cloud—always ready to learn what comes next.</p><div className="hero-actions"><a className="primary-link" href="#work">Explore my work <ArrowDown size={17}/></a><External href="https://github.com/Rakeshnamburi">GitHub</External></div></div>
 <aside className="identity-panel"><p className="eyebrow">DEVELOPMENT, WITH CURIOSITY</p><div className="identity-initials">NR<span>↗</span></div><div className="identity-lines"><span><Code2/> Thoughtful interfaces</span><span><Sparkles/> AI & LLM applications</span><span><Cloud/> Cloud foundations</span></div><div className="identity-footer">KLU · COMPUTER SCIENCE <span>CLASS OF ’26</span></div></aside></div>
 <div className="hero-bottom"><span>SOFTWARE DEVELOPMENT · AI · CLOUD</span><a href="#work">SCROLL TO DISCOVER <ArrowDown size={14}/></a></div>
 </section>
 <section id="work" className="section wrap"><div className="section-head"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made <em>real.</em></h2></div><p>Academic foundations. Independent experiments.<br/>Applications built to learn by doing.</p></div>
 <div className="filters" aria-label="Filter projects">{['All work','AI applications','Web development','Cloud & systems'].map(f=><Button key={f} variant="ghost" className={filter===f?'filter active':'filter'} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</Button>)}</div>
 <div className="project-grid">{projects.map((p,i)=>(filter==='All work'||p.category===filter)&&<article className="project-card" key={p.name}>
 <div className={'project-face '+p.tone}><span className="eyebrow">{p.label}</span><h3>{p.short}{p.second&&<><br/>{p.second}</>}<span aria-hidden="true">↗</span></h3><p>{p.line}</p></div>
 <div className="project-body"><p>{p.description}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="project-actions"><Button className="detail-button" variant="ghost" onClick={()=>setSelected(i)} aria-label={'Read about '+p.name}>Project story <ArrowUpRight size={15}/></Button>{p.live?<External href={p.live}>Live demo</External>:p.repo?<External href={p.repo}>Source code</External>:null}</div></div>
 </article>)}</div></section>
 <section id="coding" className="section wrap"><div className="section-head"><div><p className="eyebrow">02 / PROBLEM SOLVING</p><h2>Practice. Solve. <em>Repeat.</em></h2></div><p>A habit of breaking down problems<br/>and working toward a solution.</p></div>
 <div className="coding-grid"><article className="coding-card"><div className="coding-top"><Braces size={22}/><span>LEETCODE</span><External href="https://leetcode.com/u/rakeshnamburi/">View profile</External></div><div className="big-stat">744<span>problems solved</span></div><div className="difficulty"><span><i className="easy"/>201 Easy</span><span><i className="medium"/>418 Medium</span><span><i className="hard"/>125 Hard</span></div><div className="difficulty-bar" aria-hidden="true"><i/><i/><i/></div><p>Java is my most-used language on LeetCode.</p></article>
 <article className="coding-card"><div className="coding-top"><Code2 size={22}/><span>CODECHEF</span><External href="https://www.codechef.com/users/namburirakesh7">View profile</External></div><div className="big-stat">917<span>problems solved</span></div><div className="chef-facts"><span><strong>37</strong> contests participated</span><span><strong>100-day</strong> streak badge</span></div><p>Building consistency through practice and contests.</p></article></div><p className="data-note">Profile statistics checked on September 2, 2026. Visit the profiles for the latest activity.</p></section>
 <section id="about" className="section wrap about-grid"><div><p className="eyebrow">03 / THE PERSON BEHIND THE PROJECTS</p><h2>Built on learning.<br/><em>Driven by curiosity.</em></h2><p className="about-copy">I’m a Computer Science graduate who enjoys understanding how things work—and then building something with that knowledge.</p><p className="about-copy">My experience spans frontend design and development, independent AI application projects, and cloud learning. I’m also exploring LLMs, retrieval-augmented generation (RAG), and new technologies. I bring curiosity, a willingness to take feedback, and the patience to keep learning.</p><div className="education"><GraduationCap size={24}/><div><h3>Koneru Lakshmiah University</h3><p>BTech · Computer Science & Engineering</p><span>2022–2026 <b>CGPA 8.99</b></span></div></div></div><div className="skill-list">
 <div><Code2/><h3>Interfaces & development</h3><p>React · JavaScript · HTML · CSS · Tailwind CSS · Application workflow design</p></div>
 <div><Sparkles/><h3>AI & intelligent applications</h3><p>Python · Prompt engineering · LLM application development · RAG fundamentals</p></div>
 <div><Cloud/><h3>Cloud & tools</h3><p>AWS · Git & GitHub · Vercel · Microsoft Fabric learning and certification</p></div>
 <p className="learning-note">Currently exploring <span>RAG · LLMs · Emerging technologies</span></p></div></section>
 <section id="credentials" className="section wrap"><div className="section-head"><div><p className="eyebrow">04 / CONTINUOUS LEARNING</p><h2>Knowledge, with <em>evidence.</em></h2></div><p>Certifications and hands-on learning<br/>completed alongside my degree and beyond.</p></div>
 <div className="credentials">{credentials.map(([issuer,title,detail,file])=><a className="credential" key={file} href={'/certificates/'+file} target="_blank" rel="noreferrer" aria-label={'View '+title+' certificate'}><span className="credential-icon"><Award size={20}/></span><div><p>{issuer}</p><h3>{title}</h3><span>{detail}</span></div><ArrowUpRight size={18}/></a>)}</div>
 <div className="internships"><h3>Virtual internships <span>AICTE · EduSkills</span></h3><div className="internship-grid">{[
 ['Cloud','Jan–Mar 2024','Supported by AWS Academy','cloud-internship.pdf'],
 ['Data Engineering','Apr–Jun 2024','AWS Academy curriculum','data-engineering-internship.pdf'],
 ['Web Full Stack Developer','Jul–Sep 2024','Supported by EduSkills Academy','web-development-internship.pdf']
 ].map(([title,date,provider,file])=><article key={title}><span className="eyebrow">10-WEEK PROGRAM</span><h4>{title}</h4><p>{date}<br/>{provider}</p><External href={'/certificates/'+file}>View certificate</External></article>)}</div></div></section>
 <section id="community" className="section wrap"><div className="section-head"><div><p className="eyebrow">05 / BEYOND THE SCREEN</p><h2>Building with <em>people.</em></h2></div><p>Student Activity Centre · KLU</p></div><div className="community-grid"><article><Users size={27}/><div><span className="eyebrow">ELC / TEAM LEAD</span><h3>Helping a team make a difference.</h3><p>Led a team of approximately 20–25 members in college club activities promoting voting awareness and voter registration.</p><span className="community-tag">Leadership · Teamwork · Civic awareness</span></div></article><article><Heart size={27}/><div><span className="eyebrow">SAFE LIFE / MEMBER</span><h3>Small actions. Shared responsibility.</h3><p>Joined Safe Life in my first year and participated in community-awareness activities around health, diseases, and cleanliness.</p><span className="community-tag">Volunteering · Health awareness · Service</span></div></article></div></section>
 <section id="contact" className="contact wrap"><div><p className="eyebrow"><span className="status-dot"/> OPEN TO WORK, COLLABORATE & LEARN</p><h2>Have something in mind?<br/><em>Let’s build it together.</em></h2><p className="hero-copy">I’m open to early-career opportunities in software development, frontend engineering, and AI applications—and ready to grow into new challenges.</p><a className="primary-link" href="mailto:rakeshnamburi2k4@gmail.com">Say hello <ArrowUpRight size={18}/></a></div><div className="contact-links"><External href="https://www.linkedin.com/in/rakesh-namburi-a82a4b262/"><Users size={18}/> LinkedIn</External><External href="https://github.com/Rakeshnamburi"><Code2 size={18}/> GitHub</External><div className="email-line"><a href="mailto:rakeshnamburi2k4@gmail.com"><Mail size={18}/>rakeshnamburi2k4@gmail.com</a><Button variant="ghost" size="icon" onClick={copyEmail} aria-label="Copy email address">{copied?<Check size={16}/>:<Copy size={16}/>}</Button></div><span role="status" className="copy-status">{copied?'Email copied':copyError?'Please select and copy the email address above.':''}</span></div></section>
 </main><footer className="wrap footer"><span>© 2026 Namburi Rakesh</span><span>Curiosity is a work in progress.</span><a href="#">Back to top ↑</a></footer>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-dialog">{project&&<><p className="eyebrow">{project.label}</p><DialogTitle className="dialog-title">{project.name}</DialogTitle><DialogDescription>{project.description}</DialogDescription><div className="dialog-role"><span>MY ROLE</span><strong>{project.role}</strong></div><h4>The problem</h4><p>{project.problem}</p><h4>The approach</h4><p>{project.approach}</p><h4>Project highlights</h4><ul>{project.features.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{project.stack.map(s=><span key={s}>{s}</span>)}</div><p className="dialog-note">{project.note}</p><div className="project-actions">{project.live&&<External href={project.live}>Open live demo</External>}{project.repo&&<External href={project.repo}>View source</External>}</div></>}</DialogContent></Dialog>
 </>;
}


